### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by vanessahjerpe** [Edmund1645/gridsome-portfolio-story#10]
Tried a complete new project and did one change in the text. Hit publish but it doesn't publish it. Here is the netlify log.

```
11:54:19 AM: Build ready to start
11:54:21 AM: build-image version: 253f72909528f25a82c4640ca58f2e974d52abd9
11:54:21 AM: build-image tag: v3.4.4
11:54:21 AM: buildbot version: d7fbddb77714d524c4b4de0312067b122124afee
11:54:21 AM: Fetching cached dependencies
11:54:21 AM: Starting to download cache of 208.6MB
11:54:22 AM: Finished downloading cache in 1.267829409s
11:54:22 AM: Starting to extract cache
11:54:30 AM: Finished extracting cache in 7.38818218s
11:54:30 AM: Finished fetching cache in 8.728041702s
11:54:30 AM: Starting to prepare the repo for build
11:54:31 AM: Preparing Git Reference pull/2/head
11:54:32 AM: Starting build script
11:54:32 AM: Installing dependencies
11:54:32 AM: Python version set to 2.7
11:54:33 AM: Started restoring cached node version
11:54:36 AM: Finished restoring cached node version
11:54:37 AM: v12.18.0 is already installed.
11:54:37 AM: Now using node v12.18.0 (npm v6.14.4)
11:54:38 AM: Started restoring cached build plugins
11:54:38 AM: Finished restoring cached build plugins
11:54:38 AM: Attempting ruby version 2.7.1, read from environment
11:54:39 AM: Using ruby version 2.7.1
11:54:39 AM: Using PHP version 5.6
11:54:40 AM: 5.2 is already installed.
11:54:40 AM: Using Swift version 5.2
11:54:40 AM: Started restoring cached node modules
11:54:40 AM: Finished restoring cached node modules
11:54:40 AM: Started restoring cached go cache
11:54:40 AM: Finished restoring cached go cache
11:54:40 AM: go version go1.14.4 linux/amd64
11:54:40 AM: go version go1.14.4 linux/amd64
11:54:40 AM: Installing missing commands
11:54:40 AM: Verify run directory
11:54:41 AM: ​
11:54:41 AM: ┌─────────────────────────────┐
11:54:41 AM: │        Netlify Build        │
11:54:41 AM: └─────────────────────────────┘
11:54:41 AM: ​
11:54:41 AM: ❯ Version
11:54:41 AM:   @netlify/build 5.2.1
11:54:41 AM: ​
11:54:41 AM: ❯ Flags
11:54:41 AM:   deployId: 5fa52b5bd30d0e0007365bbb
11:54:41 AM:   mode: buildbot
11:54:41 AM: ​
11:54:41 AM: ❯ Current directory
11:54:41 AM:   /opt/build/repo
11:54:41 AM: ​
11:54:41 AM: ❯ Config file
11:54:41 AM:   /opt/build/repo/netlify.toml
11:54:41 AM: ​
11:54:41 AM: ❯ Context
11:54:41 AM:   deploy-preview
11:54:41 AM: ​
11:54:41 AM: ┌────────────────────────────────────┐
11:54:41 AM: │ 1. build.command from netlify.toml │
11:54:41 AM: └────────────────────────────────────┘
11:54:41 AM: ​
11:54:41 AM: $ gridsome build
11:54:42 AM: Gridsome v0.7.13
11:54:43 AM: Initializing plugins...
11:54:43 AM: Patching RemarkTransformer for Portfolio (text/markdown)
11:54:43 AM: Patching RemarkTransformer for Portfolio (text/x-markdown)
11:54:43 AM: Fixing cover images for Portfolio.cover_image
11:54:43 AM: Load sources - 0.07s
11:54:43 AM: Create GraphQL schema - 0.08s
11:54:43 AM: Create pages and templates - 0.05s
11:54:43 AM: Generate temporary code - 0.03s
11:54:43 AM: Bootstrap finish - 1.34s
11:54:43 AM: Compiling assets...
11:54:45 AM: Browserslist: caniuse-lite is outdated. Please run:
11:54:45 AM: npx browserslist@latest --update-db
11:54:56 AM: Compile assets - 12.96s
11:54:58 AM: Execute GraphQL (15 queries) - 1.84s
11:54:58 AM: Write out page data (15 files) - 0.01s
11:54:59 AM: Could not generate HTML for "/tag/product%20design/":
11:54:59 AM: TypeError: Cannot read property 'src' of null
11:54:59 AM:     at render (node_modules/gridsome/app/components/Image.js:36:16)
11:54:59 AM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:22507
11:54:59 AM:     at Ie (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:22689)
11:54:59 AM:     at /opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:23819
11:54:59 AM:     at Le (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:24170)
11:54:59 AM:     at e._c (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:32380)
11:54:59 AM:     at a.render (src/components/WorkCard.vue?0c31:1:130)
11:54:59 AM:     at a.t._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
11:54:59 AM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70603
11:54:59 AM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67167)
11:54:59 AM: ​
11:54:59 AM: ┌─────────────────────────────┐
11:54:59 AM: │   "build.command" failed    │
11:54:59 AM: └─────────────────────────────┘
11:54:59 AM: ​
11:54:59 AM:   Error message
11:54:59 AM:   Command failed with exit code 1: gridsome build
11:54:59 AM: ​
11:54:59 AM:   Error location
11:54:59 AM:   In build.command from netlify.toml:
11:54:59 AM:   gridsome build
11:54:59 AM: ​
11:54:59 AM:   Resolved config
11:54:59 AM:   build:
11:54:59 AM:     command: gridsome build
11:54:59 AM:     commandOrigin: config
11:54:59 AM:     environment:
11:54:59 AM:       - REVIEW_ID
11:54:59 AM:     publish: /opt/build/repo/dist
11:54:59 AM: Caching artifacts
11:54:59 AM: Started saving node modules
11:54:59 AM: Finished saving node modules
11:54:59 AM: Started saving build plugins
11:54:59 AM: Finished saving build plugins
11:54:59 AM: Started saving pip cache
11:54:59 AM: Finished saving pip cache
11:54:59 AM: Started saving emacs cask dependencies
11:54:59 AM: Finished saving emacs cask dependencies
11:54:59 AM: Started saving maven dependencies
11:55:00 AM: Finished saving maven dependencies
11:55:00 AM: Started saving boot dependencies
11:55:00 AM: Finished saving boot dependencies
11:55:00 AM: Started saving go dependencies
11:55:00 AM: Finished saving go dependencies
11:55:00 AM: Build failed due to a user error: Build script returned non-zero exit code: 2
11:55:00 AM: Failing build: Failed to build site
11:55:00 AM: Failed during stage 'building site': Build script returned non-zero exit code: 2
11:55:00 AM: Finished processing build request in 38.688190901s
```

**Comment by Edmund1645** [comment]
Hi @vanessahjerpe, Can I get a sample repo with this same problem please?

**Comment by vanessahjerpe** [comment]
Creating a new one right now to send you, doing the changes with the netlify admin site, that should work right?

**Comment by Edmund1645** [comment]
Yeah it should, i just need a sample repo with that issue, if you could set it up as you did earlier that'd be great

**Comment by vanessahjerpe** [comment]
The first the I just removed a whole project which worked fine from the admin site. Then the second time I just removed some text in an existing project in the admin site and now the PR won't build

https://github.com/vanessahjerpe/personal-portfolio

**Comment by vanessahjerpe** [comment]
I could see that the changes here doesn't really reflect the actual change from the admin site: https://github.com/vanessahjerpe/personal-portfolio/pull/1/commits/8b9587e66d902dd804b66e7a83fceb15362ef022

I didn't do anything to the tags, date etc.
